# Generated by Django 4.1.2 on 2022-10-10 05:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(blank=True, max_length=512)),
                ('refresh', models.CharField(blank=True, max_length=512)),
                ('access_expiration', models.DateTimeField(default=datetime.datetime(2022, 10, 10, 6, 39, 55, 501668))),
                ('refresh_expiration', models.DateTimeField(default=datetime.datetime(2022, 10, 13, 5, 49, 55, 501685))),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
